### ISSUE TITLE
[Discussion] Some ground rules we need to agree on

### ISSUE THREAD

**Issue by onimsha** [findgeek/geekjob#1]
# Motivation  
We need to have some basic rules for maintain this repo, such as the medium of job posting, spam filter, approval process. 

# Medium of job posting  
I was wondering if we use Github Issues for the job posting. While it's pretty easy to use Issue, it's quite difficult for navigation because people have to put some search & filter which i think, is bad for UX.   

My proposal is we put the job posting as the Markdown file inside the repo, and use PR as approval method. With this, we can add the Table of Contents into the README.md for quick navigation, similar to the awesome-xxx repos.   

The README.md will acts as the home page, with the Table of Contents will contains the links to the actual jobs, grouped by country / region. Another file, GUIDELINES.md will contains the job posting rules & format.   

# Spam filter  
When someone submit a PR, repo Maintainers will check the contents and flag the PR as spam / agency if needed. Or if we have a bot, we can expose some command for house-keeping work. Flagged PR without any updates will be closed automatically after 30 days.  

# Approval process  
Maintainers are the ones who give the approval. Each PR should requires at least 2 approval (?). Later on when we have more traction, we can switch to voting mechanism using reaction.  

LMK what you think

**Comment by vn-patriot** [comment]
Hi @onimsha  i literally agree with you focusing on the main ideas. However just want to extend few more things 

1. Medium of Job posting 

- Agree to ask people create the Pull Request instead of using the issues page. However what will folder structure be ? 

Like example : 

_based on the date time_ of job posting. Example today is 10/Oct/2020. So we will create all the date folders from today till the last day of the month.
- 2020-Oct-11
- 2020-Oct-12
...
...
And inside of each folder we will put each of job as a file following the explicit title name like 
**[US] Senior DevOps - Company A - FullTime / Remote.md**

The pros of this way is : we easily calculate how many jobs were posted - well organized (from my point of view)
The cons : who fucking care about the date time job posting ? If i was the candidate, i would only care about what was that job 

_based on the title_. So let's say our job title is very low hanging fruit as we don't have so many jobs in IT world nowadays. We will create the folders in prior  

- Devops 
- SRE 
- Cloud Engineer
- QA 
- Software FrontEnd
- Software Backend
- Android 
- iOS

Pros : very straight forward to adapt their demand
Cons : i don't see  :D 

_based on the country_ another important thing like every geeks used to care. Where that job would be. Needless to say our structure will 

- US
- CA 
- DE
- NL 

Pros : ok it's fine to who keen to relocate :) (it might be wrong because the job posted in DE doesn't mean that support relocation)
Cons : comparing with the job title, this is a loser 

_Based on the tech stack_ Also 1 important thing to care about, however the tech stack is something quite general because person can handle more than 1 stack. So as long as they feel comfortable with other things. I don't think tech stack would be so important.

I **voted for Title structure**. Kindly to let me know your thought.

2. Spam filter 

I firmly believe this is what we can handle, i can create some required label before people submit their pr, they will need to select them first. If not they will not able to submit :) 

3. Approval process 

I think 2 approvals from admin(s) is a best scenario but 1 is acceptable. For now i would encourage everyone posting the job first and later on we can require it a little bit more difficult on the content.  

Thank you very much

cc @ngoduykhanh

**Comment by onimsha** [comment]
Yeah i think using category-based is a good way too. +1 

> I firmly believe this is what we can handle, i can create some required label before people submit their pr, they will need to select them first. If not they will not able to submit :). 

Labelling should be on maintainer side, with (possible) help from bot. I suggest following set of labels:
* `waiting-for-review` : Newly created PR and need to review
* `wrong-format` : PR that does not conform with guidelines and need to be updated
* `spam` : Spam PR , will be closed automatically 
* `recruitment-agency` :  PR that came from agency, not direct employer

**Comment by ngoduykhanh** [comment]
I think the biggest diff between 2 methods - Issue and PR/RepoFile is about discussion and state.
With Issue, people can easily comment on the Job to start a conversation. With PR, once it got merged to be displayed as RepoFile, it will be closed, in this state, it is not supposed to have more discussion anymore. On another hand, when an Issue is closed, it means Job is closed, no discussion anymore.
Talking about the searching, I think Issue still better, Github support a dedicated search form for that. RepoFile searching works, however, it isn't nice to me.
Talking about navigation, yes, RepoFile is better, but with a small number of files...

**Comment by onimsha** [comment]
It's true that using Issues will create more engagements / discussion rather than using PR, i was thinking about that also. However during the discussion with Toan, the discussion should happens mostly on Telegram. The Github repo will act as a centralised database, so people can browse the contents easier.

**Comment by ngoduykhanh** [comment]
If that is the case, it makes sense. We can use it as the sources for other platforms as well (automated).
